[2023-12-07T00:31:55.696+0000] {processor.py:157} INFO - Started process (PID=1657) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:31:55.697+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:31:55.699+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:31:55.698+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:31:56.790+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:31:56.787+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:31:56.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:31:56.818+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.127 seconds
[2023-12-07T00:32:27.201+0000] {processor.py:157} INFO - Started process (PID=1679) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:27.204+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:32:27.208+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:32:27.206+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:27.976+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:32:27.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:32:27.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:27.992+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.799 seconds
[2023-12-07T00:32:58.515+0000] {processor.py:157} INFO - Started process (PID=1701) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:58.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:32:58.518+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:32:58.518+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:59.058+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:32:59.057+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:32:59.059+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:32:59.071+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.561 seconds
[2023-12-07T00:33:29.530+0000] {processor.py:157} INFO - Started process (PID=1723) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:33:29.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:33:29.533+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:33:29.533+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:33:30.052+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:33:30.051+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:33:30.053+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:33:30.063+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.539 seconds
[2023-12-07T00:34:00.291+0000] {processor.py:157} INFO - Started process (PID=1745) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:00.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:34:00.293+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:34:00.293+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:00.844+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:34:00.843+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:34:00.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:00.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.570 seconds
[2023-12-07T00:34:31.330+0000] {processor.py:157} INFO - Started process (PID=1767) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:31.332+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:34:31.334+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:34:31.333+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:31.852+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:34:31.851+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:34:31.853+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:34:31.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.540 seconds
[2023-12-07T00:35:02.026+0000] {processor.py:157} INFO - Started process (PID=1789) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:02.028+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:35:02.029+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:35:02.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:02.544+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:35:02.543+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:35:02.545+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:02.558+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.537 seconds
[2023-12-07T00:35:32.904+0000] {processor.py:157} INFO - Started process (PID=1811) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:32.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:35:32.906+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:35:32.905+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:33.407+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:35:33.406+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:35:33.408+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:35:33.418+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.517 seconds
[2023-12-07T00:36:03.846+0000] {processor.py:157} INFO - Started process (PID=1833) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:03.847+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:36:03.848+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:36:03.848+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:04.363+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:36:04.361+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:36:04.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:04.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.533 seconds
[2023-12-07T00:36:34.712+0000] {processor.py:157} INFO - Started process (PID=1855) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:34.714+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:36:34.715+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:36:34.715+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:35.225+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:36:35.223+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:36:35.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:36:35.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.528 seconds
[2023-12-07T00:37:05.676+0000] {processor.py:157} INFO - Started process (PID=1877) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:37:05.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:37:05.679+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:37:05.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:37:06.187+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:37:06.186+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:37:06.187+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:37:06.197+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.526 seconds
[2023-12-07T00:38:11.868+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:11.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:38:11.870+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:38:11.870+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:13.093+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:38:13.091+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:38:13.093+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:13.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.241 seconds
[2023-12-07T00:38:43.214+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:43.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:38:43.217+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:38:43.216+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:43.965+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:38:43.963+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:38:43.965+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:38:43.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.768 seconds
[2023-12-07T00:39:14.455+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:14.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:39:14.459+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:39:14.459+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:15.058+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:39:15.056+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:39:15.058+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:15.072+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.622 seconds
[2023-12-07T00:39:45.231+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:45.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:39:45.234+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:39:45.233+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:45.979+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:39:45.977+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:39:45.979+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:39:45.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.768 seconds
[2023-12-07T00:40:16.497+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:16.499+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:40:16.501+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:40:16.500+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:17.035+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:40:17.034+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:40:17.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:17.046+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.556 seconds
[2023-12-07T00:40:47.139+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:47.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:40:47.144+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:40:47.143+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:47.783+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:40:47.782+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:40:47.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:40:47.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.663 seconds
[2023-12-07T00:41:18.178+0000] {processor.py:157} INFO - Started process (PID=302) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:18.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:41:18.181+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:41:18.181+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:18.699+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:41:18.697+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:41:18.699+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:18.710+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.537 seconds
[2023-12-07T00:41:49.101+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:49.104+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:41:49.105+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:41:49.105+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:49.706+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:41:49.705+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:41:49.707+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:41:49.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.622 seconds
[2023-12-07T00:42:48.471+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:42:48.472+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:42:48.473+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:42:48.473+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:42:49.572+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:42:49.571+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:42:49.573+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:42:49.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.115 seconds
[2023-12-07T00:43:19.823+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:19.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:43:19.825+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:43:19.825+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:20.399+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:43:20.397+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:43:20.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:20.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.592 seconds
[2023-12-07T00:43:50.809+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:50.812+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:43:50.814+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:43:50.813+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:51.384+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:43:51.383+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:43:51.385+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:43:51.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.594 seconds
[2023-12-07T00:44:21.462+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:21.464+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:44:21.465+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:44:21.465+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:22.000+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:44:21.998+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:44:22.000+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:22.013+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.556 seconds
[2023-12-07T00:44:52.100+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:52.101+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:44:52.102+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:44:52.102+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:52.614+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:44:52.613+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:44:52.615+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:44:52.625+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.528 seconds
[2023-12-07T00:45:22.825+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:22.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:45:22.829+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:45:22.829+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:23.349+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:45:23.348+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:45:23.349+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:23.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.540 seconds
[2023-12-07T00:45:53.782+0000] {processor.py:157} INFO - Started process (PID=302) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:53.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:45:53.783+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:45:53.783+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:54.290+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:45:54.289+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:45:54.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:45:54.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.523 seconds
[2023-12-07T00:46:24.716+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:24.718+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:46:24.719+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:46:24.719+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:25.238+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:46:25.237+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:46:25.239+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:25.249+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.538 seconds
[2023-12-07T00:46:55.675+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:55.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:46:55.678+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:46:55.678+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:56.191+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:46:56.189+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:46:56.191+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:46:56.202+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.532 seconds
[2023-12-07T00:47:26.358+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:26.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:47:26.361+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:47:26.361+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:26.872+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:47:26.870+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:47:26.872+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:26.883+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.530 seconds
[2023-12-07T00:47:56.975+0000] {processor.py:157} INFO - Started process (PID=390) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:56.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:47:56.979+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:47:56.979+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:57.486+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:47:57.485+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:47:57.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:47:57.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.527 seconds
[2023-12-07T00:48:27.655+0000] {processor.py:157} INFO - Started process (PID=412) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:27.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:48:27.658+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:48:27.658+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:28.166+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:48:28.164+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:48:28.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:28.177+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.527 seconds
[2023-12-07T00:48:58.234+0000] {processor.py:157} INFO - Started process (PID=434) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:58.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:48:58.236+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:48:58.236+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:58.786+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:48:58.785+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:48:58.787+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:48:58.797+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.565 seconds
[2023-12-07T00:49:28.961+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:49:28.962+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:49:28.963+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:49:28.963+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:49:29.481+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:49:29.479+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:49:29.481+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:49:29.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.534 seconds
[2023-12-07T00:49:59.873+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:49:59.874+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:49:59.875+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:49:59.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:50:00.423+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:50:00.421+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:50:00.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:50:00.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.566 seconds
[2023-12-07T00:50:30.876+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:50:30.878+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:50:30.879+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:50:30.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:50:31.399+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:50:31.397+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:50:31.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:50:31.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.540 seconds
[2023-12-07T00:51:01.554+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T00:51:01.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T00:51:01.557+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:51:01.557+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:51:02.086+0000] {logging_mixin.py:154} INFO - [2023-12-07T00:51:02.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T00:51:02.087+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T00:51:02.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.549 seconds
[2023-12-07T01:05:52.106+0000] {processor.py:157} INFO - Started process (PID=544) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:05:52.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:05:52.108+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:05:52.108+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:05:52.892+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:05:52.890+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:05:52.893+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:05:52.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.821 seconds
[2023-12-07T01:06:23.341+0000] {processor.py:157} INFO - Started process (PID=568) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:23.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:06:23.345+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:06:23.344+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:23.917+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:06:23.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:06:23.917+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:23.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.593 seconds
[2023-12-07T01:06:54.056+0000] {processor.py:157} INFO - Started process (PID=590) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:54.058+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:06:54.059+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:06:54.059+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:54.595+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:06:54.593+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:06:54.595+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:06:54.605+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.555 seconds
[2023-12-07T01:07:25.006+0000] {processor.py:157} INFO - Started process (PID=612) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:25.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:07:25.010+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:07:25.009+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:25.584+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:07:25.583+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:07:25.585+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:25.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.596 seconds
[2023-12-07T01:07:56.006+0000] {processor.py:157} INFO - Started process (PID=634) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:56.008+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:07:56.008+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:07:56.008+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:56.522+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:07:56.521+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:07:56.523+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:07:56.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.530 seconds
[2023-12-07T01:08:26.767+0000] {processor.py:157} INFO - Started process (PID=656) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:26.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:08:26.770+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:08:26.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:27.306+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:08:27.305+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:08:27.307+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:27.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.554 seconds
[2023-12-07T01:08:57.676+0000] {processor.py:157} INFO - Started process (PID=678) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:57.678+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:08:57.679+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:08:57.679+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:58.225+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:08:58.224+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:08:58.226+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:08:58.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.566 seconds
[2023-12-07T01:09:28.684+0000] {processor.py:157} INFO - Started process (PID=700) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:09:28.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:09:28.690+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:09:28.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:09:29.324+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:09:29.322+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 2, in <module>
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:09:29.324+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:09:29.338+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.659 seconds
[2023-12-07T01:09:59.751+0000] {processor.py:157} INFO - Started process (PID=722) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:09:59.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:09:59.755+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:09:59.755+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:10:00.359+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:10:00.358+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.tracking.client import MlflowClient
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:10:00.360+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:10:00.370+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.624 seconds
[2023-12-07T01:10:30.473+0000] {processor.py:157} INFO - Started process (PID=744) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:10:30.478+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:10:30.479+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:10:30.479+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:10:31.056+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:10:31.055+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.tracking.client import MlflowClient
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:10:31.057+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:10:31.070+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.602 seconds
[2023-12-07T01:11:01.440+0000] {processor.py:157} INFO - Started process (PID=766) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:01.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:11:01.443+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:11:01.443+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:02.022+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:11:02.020+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 10, in <module>
    from xgboost import XGBClassifier
ModuleNotFoundError: No module named 'xgboost'
[2023-12-07T01:11:02.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:02.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.597 seconds
[2023-12-07T01:11:32.397+0000] {processor.py:157} INFO - Started process (PID=788) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:32.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:11:32.402+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:11:32.402+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:32.975+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:11:32.974+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 10, in <module>
    from xgboost import XGBClassifier
ModuleNotFoundError: No module named 'xgboost'
[2023-12-07T01:11:32.976+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:11:32.987+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.595 seconds
[2023-12-07T01:12:03.343+0000] {processor.py:157} INFO - Started process (PID=810) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:03.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:12:03.346+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:12:03.346+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:03.962+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:12:03.960+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 136, in <module>
    rf_hyperoptimization()
  File "/opt/airflow/dags/src/random_forest_model.py", line 99, in rf_hyperoptimization
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:12:03.962+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:03.974+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.634 seconds
[2023-12-07T01:12:34.323+0000] {processor.py:157} INFO - Started process (PID=832) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:34.326+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:12:34.327+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:12:34.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:34.912+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:12:34.911+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 136, in <module>
    rf_hyperoptimization()
  File "/opt/airflow/dags/src/random_forest_model.py", line 99, in rf_hyperoptimization
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:12:34.913+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:12:34.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.606 seconds
[2023-12-07T01:13:05.280+0000] {processor.py:157} INFO - Started process (PID=854) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:05.281+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:13:05.282+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:13:05.282+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:05.875+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:13:05.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 136, in <module>
    rf_hyperoptimization()
  File "/opt/airflow/dags/src/random_forest_model.py", line 99, in rf_hyperoptimization
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:13:05.876+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:05.891+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.613 seconds
[2023-12-07T01:13:36.001+0000] {processor.py:157} INFO - Started process (PID=876) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:36.002+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:13:36.003+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:13:36.002+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:36.577+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:13:36.576+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 136, in <module>
    rf_hyperoptimization()
  File "/opt/airflow/dags/src/random_forest_model.py", line 99, in rf_hyperoptimization
    import mlflow
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:13:36.578+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:13:36.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.590 seconds
[2023-12-07T01:14:06.895+0000] {processor.py:157} INFO - Started process (PID=898) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:06.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:14:06.901+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:14:06.900+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:07.478+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:14:07.476+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 12, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:14:07.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:07.489+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.598 seconds
[2023-12-07T01:14:37.910+0000] {processor.py:157} INFO - Started process (PID=920) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:37.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:14:37.915+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:14:37.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:38.455+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:14:38.453+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:14:38.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:14:38.467+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.562 seconds
[2023-12-07T01:15:08.589+0000] {processor.py:157} INFO - Started process (PID=942) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:08.591+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:15:08.592+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:15:08.592+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:09.200+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:15:09.198+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:15:09.200+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:09.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.625 seconds
[2023-12-07T01:15:39.609+0000] {processor.py:157} INFO - Started process (PID=971) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:39.610+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:15:39.611+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:15:39.611+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:40.140+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:15:40.139+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:15:40.141+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:15:40.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.547 seconds
[2023-12-07T01:16:10.496+0000] {processor.py:157} INFO - Started process (PID=993) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:10.498+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:16:10.499+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:16:10.499+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:11.150+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:16:11.149+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:16:11.151+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:11.162+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.669 seconds
[2023-12-07T01:16:41.485+0000] {processor.py:157} INFO - Started process (PID=1015) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:41.487+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:16:41.488+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:16:41.488+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:42.063+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:16:42.062+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:16:42.064+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:16:42.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.596 seconds
[2023-12-07T01:17:12.556+0000] {processor.py:157} INFO - Started process (PID=1037) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:12.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:17:12.559+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:17:12.558+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:13.107+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:17:13.106+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:17:13.108+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:13.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.569 seconds
[2023-12-07T01:17:43.228+0000] {processor.py:157} INFO - Started process (PID=1059) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:43.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:17:43.236+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:17:43.236+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:43.814+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:17:43.812+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:17:43.815+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:17:43.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.601 seconds
[2023-12-07T01:18:13.889+0000] {processor.py:157} INFO - Started process (PID=1081) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:18:13.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:18:13.892+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:18:13.892+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:18:14.495+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:18:14.493+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:18:14.495+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:18:14.507+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.624 seconds
[2023-12-07T01:19:38.537+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:19:38.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:19:38.539+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:19:38.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:19:39.900+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:19:39.899+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:19:39.901+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:19:39.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.379 seconds
[2023-12-07T01:20:10.328+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:10.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:20:10.332+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:20:10.331+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:10.987+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:20:10.985+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:20:10.987+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:10.998+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.676 seconds
[2023-12-07T01:20:41.183+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:41.185+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:20:41.186+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:20:41.186+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:41.952+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:20:41.950+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:20:41.953+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:20:41.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.789 seconds
[2023-12-07T01:21:12.392+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:12.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:21:12.394+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:21:12.394+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:13.159+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:21:13.157+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:21:13.159+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:13.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.788 seconds
[2023-12-07T01:21:43.596+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:43.601+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:21:43.602+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:21:43.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:44.158+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:21:44.156+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:21:44.158+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:21:44.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.578 seconds
[2023-12-07T01:22:14.304+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:14.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:22:14.309+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:22:14.308+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:15.108+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:22:15.107+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:22:15.109+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:15.121+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.820 seconds
[2023-12-07T01:22:45.583+0000] {processor.py:157} INFO - Started process (PID=302) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:45.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:22:45.590+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:22:45.589+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:46.374+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:22:46.372+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:22:46.375+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:22:46.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.810 seconds
[2023-12-07T01:23:16.789+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:16.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:23:16.792+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:23:16.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:17.518+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:23:17.516+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:23:17.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:17.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.749 seconds
[2023-12-07T01:23:47.824+0000] {processor.py:157} INFO - Started process (PID=346) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:47.826+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:23:47.827+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:23:47.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:48.451+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:23:48.449+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:23:48.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:23:48.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.644 seconds
[2023-12-07T01:24:18.922+0000] {processor.py:157} INFO - Started process (PID=368) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:18.923+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:24:18.925+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:24:18.924+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:19.642+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:24:19.639+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:24:19.643+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:19.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.750 seconds
[2023-12-07T01:24:49.759+0000] {processor.py:157} INFO - Started process (PID=390) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:49.761+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:24:49.762+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:24:49.761+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:50.335+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:24:50.333+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:24:50.336+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:24:50.348+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.593 seconds
[2023-12-07T01:25:20.601+0000] {processor.py:157} INFO - Started process (PID=412) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:20.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:25:20.605+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:25:20.604+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:21.332+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:25:21.330+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:25:21.333+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:21.346+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.753 seconds
[2023-12-07T01:25:51.729+0000] {processor.py:157} INFO - Started process (PID=434) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:51.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:25:51.733+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:25:51.732+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:52.291+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:25:52.289+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:25:52.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:25:52.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.579 seconds
[2023-12-07T01:26:22.523+0000] {processor.py:157} INFO - Started process (PID=456) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:22.524+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:26:22.524+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:26:22.524+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:23.085+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:26:23.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:26:23.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:23.097+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.577 seconds
[2023-12-07T01:26:53.542+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:53.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:26:53.544+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:26:53.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:54.279+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:26:54.277+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:26:54.280+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:26:54.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.755 seconds
[2023-12-07T01:27:24.581+0000] {processor.py:157} INFO - Started process (PID=500) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:24.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:27:24.584+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:27:24.583+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:25.534+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:27:25.532+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:27:25.535+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:25.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.974 seconds
[2023-12-07T01:27:55.864+0000] {processor.py:157} INFO - Started process (PID=522) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:55.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:27:55.866+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:27:55.866+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:56.486+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:27:56.484+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:27:56.487+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:27:56.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.636 seconds
[2023-12-07T01:28:26.885+0000] {processor.py:157} INFO - Started process (PID=544) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:26.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:28:26.889+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:28:26.888+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:27.689+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:28:27.687+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:28:27.689+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:27.703+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.825 seconds
[2023-12-07T01:28:57.777+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:57.778+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:28:57.779+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:28:57.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:58.314+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:28:58.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:28:58.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:28:58.325+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.551 seconds
[2023-12-07T01:29:28.499+0000] {processor.py:157} INFO - Started process (PID=588) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:28.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:29:28.502+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:29:28.501+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:29.048+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:29:29.046+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:29:29.048+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:29.059+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.566 seconds
[2023-12-07T01:29:59.155+0000] {processor.py:157} INFO - Started process (PID=610) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:59.157+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:29:59.158+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:29:59.158+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:59.858+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:29:59.857+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:29:59.859+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:29:59.873+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.724 seconds
[2023-12-07T01:30:40.894+0000] {processor.py:157} INFO - Started process (PID=632) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:30:40.896+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:30:40.897+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:30:40.897+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:30:41.486+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:30:41.484+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:30:41.486+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:30:41.498+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.609 seconds
[2023-12-07T01:31:43.165+0000] {processor.py:157} INFO - Started process (PID=656) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:31:43.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:31:43.173+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:31:43.172+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:31:43.823+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:31:43.821+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:31:43.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:31:43.836+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.677 seconds
[2023-12-07T01:32:59.917+0000] {processor.py:157} INFO - Started process (PID=679) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:32:59.919+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:32:59.920+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:32:59.920+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:33:00.518+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:33:00.516+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:33:00.518+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:33:00.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.616 seconds
[2023-12-07T01:33:30.660+0000] {processor.py:157} INFO - Started process (PID=702) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:33:30.662+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:33:30.664+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:33:30.663+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:33:31.207+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:33:31.206+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:33:31.208+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:33:31.218+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.563 seconds
[2023-12-07T01:37:57.115+0000] {processor.py:157} INFO - Started process (PID=724) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:37:57.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:37:57.120+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:37:57.119+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:37:58.387+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:37:58.385+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:37:58.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:37:58.403+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.296 seconds
[2023-12-07T01:38:28.784+0000] {processor.py:157} INFO - Started process (PID=746) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:38:28.786+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:38:28.787+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:38:28.787+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:38:29.423+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:38:29.421+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:38:29.423+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:38:29.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.658 seconds
[2023-12-07T01:46:27.929+0000] {processor.py:157} INFO - Started process (PID=171) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:46:27.931+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:46:27.931+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:46:27.931+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:46:30.111+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:46:30.110+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:46:30.112+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:46:30.125+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 2.199 seconds
[2023-12-07T01:47:00.262+0000] {processor.py:157} INFO - Started process (PID=193) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:00.264+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:47:00.265+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:47:00.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:00.895+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:47:00.893+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:47:00.895+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:00.907+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.649 seconds
[2023-12-07T01:47:31.326+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:31.327+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:47:31.328+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:47:31.327+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:31.917+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:47:31.916+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:47:31.918+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:47:31.932+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.608 seconds
[2023-12-07T01:48:02.287+0000] {processor.py:157} INFO - Started process (PID=237) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:02.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:48:02.289+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:48:02.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:02.936+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:48:02.934+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:48:02.937+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:02.947+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.640 seconds
[2023-12-07T01:48:33.254+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:33.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:48:33.259+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:48:33.258+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:33.817+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:48:33.816+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:48:33.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:48:33.827+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.579 seconds
[2023-12-07T01:49:04.009+0000] {processor.py:157} INFO - Started process (PID=281) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:04.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:49:04.012+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:49:04.012+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:04.665+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:49:04.663+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:49:04.666+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:04.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.674 seconds
[2023-12-07T01:49:34.961+0000] {processor.py:157} INFO - Started process (PID=303) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:34.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:49:34.968+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:49:34.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:35.513+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:49:35.511+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:49:35.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:49:35.522+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.567 seconds
[2023-12-07T01:50:05.758+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:05.759+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:50:05.760+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:05.760+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:06.315+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:06.313+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:50:06.315+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:06.326+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.573 seconds
[2023-12-07T01:50:32.772+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:32.777+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:50:32.778+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:32.778+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:33.940+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:33.938+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:50:33.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:33.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.184 seconds
[2023-12-07T01:50:36.596+0000] {processor.py:157} INFO - Started process (PID=347) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:36.598+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:50:36.599+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:36.599+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:37.183+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:50:37.182+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:50:37.184+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:50:37.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.603 seconds
[2023-12-07T01:51:04.046+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:04.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:51:04.050+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:51:04.050+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:04.654+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:51:04.652+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:51:04.655+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:04.666+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.623 seconds
[2023-12-07T01:51:07.470+0000] {processor.py:157} INFO - Started process (PID=369) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:07.472+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:51:07.474+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:51:07.473+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:08.085+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:51:08.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:51:08.085+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:08.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.633 seconds
[2023-12-07T01:51:35.018+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:51:35.022+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:51:35.024+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:51:35.023+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:08.937+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:08.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:52:08.953+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:52:08.953+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:10.186+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:52:10.163+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:52:10.189+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:10.200+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.266 seconds
[2023-12-07T01:52:40.520+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:40.521+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:52:40.522+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:52:40.522+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:41.174+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:52:41.171+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:52:41.176+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:52:41.189+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.673 seconds
[2023-12-07T01:53:11.585+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:11.587+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:53:11.589+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:53:11.589+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:12.259+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:53:12.257+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:53:12.260+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:12.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.698 seconds
[2023-12-07T01:53:42.623+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:42.624+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:53:42.625+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:53:42.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:43.334+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:53:43.332+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:53:43.335+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:53:43.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.730 seconds
[2023-12-07T01:54:13.782+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:13.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:54:13.784+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:54:13.784+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:14.539+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:54:14.537+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:54:14.539+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:14.553+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.777 seconds
[2023-12-07T01:54:45.032+0000] {processor.py:157} INFO - Started process (PID=280) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:45.034+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:54:45.035+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:54:45.035+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:45.644+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:54:45.642+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:54:45.644+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:54:45.658+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.629 seconds
[2023-12-07T01:55:15.850+0000] {processor.py:157} INFO - Started process (PID=302) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:15.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:55:15.856+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:55:15.855+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:16.438+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:55:16.436+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:55:16.438+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:16.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.604 seconds
[2023-12-07T01:55:46.785+0000] {processor.py:157} INFO - Started process (PID=324) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:46.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:55:46.787+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:55:46.787+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:47.464+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:55:47.462+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:55:47.465+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:55:47.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.696 seconds
[2023-12-07T01:58:02.701+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:02.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:58:02.704+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:58:02.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:04.085+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:58:04.083+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:58:04.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:04.101+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.403 seconds
[2023-12-07T01:58:34.422+0000] {processor.py:157} INFO - Started process (PID=192) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:34.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:58:34.425+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:58:34.424+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:35.091+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:58:35.089+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:58:35.091+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:58:35.108+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.689 seconds
[2023-12-07T01:59:05.292+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:05.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:59:05.296+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:59:05.296+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:05.939+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:59:05.937+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:59:05.940+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:05.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.664 seconds
[2023-12-07T01:59:36.326+0000] {processor.py:157} INFO - Started process (PID=236) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:36.328+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T01:59:36.328+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:59:36.328+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:36.866+0000] {logging_mixin.py:154} INFO - [2023-12-07T01:59:36.864+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T01:59:36.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T01:59:36.877+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 0.553 seconds
[2023-12-07T02:00:25.120+0000] {processor.py:157} INFO - Started process (PID=170) to work on /opt/airflow/dags/airflow_code.py
[2023-12-07T02:00:25.124+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/airflow_code.py for tasks to queue
[2023-12-07T02:00:25.125+0000] {logging_mixin.py:154} INFO - [2023-12-07T02:00:25.124+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/airflow_code.py
[2023-12-07T02:00:26.362+0000] {logging_mixin.py:154} INFO - [2023-12-07T02:00:26.361+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/airflow_code.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow_code.py", line 10, in <module>
    from src.random_forest_model import rf_hyperoptimization
  File "/opt/airflow/dags/src/random_forest_model.py", line 9, in <module>
    from mlflow.models.signature import infer_signature
ModuleNotFoundError: No module named 'mlflow'
[2023-12-07T02:00:26.363+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow_code.py
[2023-12-07T02:00:26.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/airflow_code.py took 1.259 seconds
